# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.PositiveIntegerField()),
                ('company_name', models.CharField(max_length=50)),
                ('money_limit', models.PositiveIntegerField(default=0)),
                ('priority', models.IntegerField(default=0)),
            ],
        ),
    ]
